### ISSUE TITLE
API Changed since blockchain halted?

### ISSUE THREAD

**Issue by thxcks** [co8/HDS#38] opened 2021-11-19 13:01 UTC
Hi Co8, 

Love the app - some really great work!

I actually came across and got this setup during the outage this week - so it had not been working after I had set it up due to the API issues.

It then started to work on Nov 17th and outputted ~20 messages, but then stopped working again on Nov 18th at 4:34 AM - with no changes made by myself.

When I run the command manually now I am getting:

`12:58 11/19/21 Activity API Error: Parsing JSON`

Has the API results been changed do you know and it is now pending an update from you?

Or is my installation somehow just having some issues and yours / others are still working fine?

 I am not familiar enough with Python to be able to diagnose myself.

Thanks in advance for your time!

**Comment by n3phz** [comment] 2021-11-19 14:55
Hello,

I was about to write about this too.

I haven't changed anything, and I am getting the same error:

14:54 11/19/21 Activity API Error: Parsing JSON

It is happening since the API outage of yesterday

last message on discord:
Yesterday at 4:21 AM

Thank you!

**Comment by relaxpn** [comment] 2021-11-19 20:15
The problem is that the helium API keeps returning the 429 status code (too many requests) for the python script so there is no JSON to parse.
If you try to open the activity URL manually in the browser it works without any issue so I'm not sure how we are rate limited in this case.

**Comment by thxcks** [comment] 2021-11-19 21:05
Thanks for the reply @relaxpn.

Do you run the script locally?

I don't, so could be the reason it works in my browser - but I could set up a tunnel to the machine in runs on and open in a browser to see if the browser is then blocked. (If anyone runs locally and can confirm would probably be easier?)

Alternatively, I can only assume the limit is coming from the default user-agent, I wonder if setting a browser user-agent header on the python requests would work?

Assuming @co8 doesn't sort beforehand of course (Maybe Helium Devs can allow a custom user agent whitelist considering this tool is listed in community tools now)!

**Comment by relaxpn** [comment] 2021-11-19 21:07
@thxcks On my raspberry pi, it definetly has to do something with the default user agent, as soon as I changed it to something else it worked!

**Comment by co8** [comment] 2021-11-19 21:15
Great to see folks using HDS!

@relaxpn can you expand on what you did? 

1 request per min should not be an issue, even from thousands of users. But the public API can be subject to abuse.

I'm looking into the API issues. I'm not sure yet if it's due to the outage issues, or changes to the API format, or perhaps changes related to POCv11.

I appreciate everyone's input!
-e

**Comment by relaxpn** [comment] 2021-11-19 21:27
@co8 I'll create a PR.

**Comment by co8** [comment] 2021-11-20 15:35
@relaxpn pr has been merged as a fix. thanks!

**Closed as completed by co8** 2021-11-20 15:35 UTC
